version: "3.7"

networks:
  devcrown:
    driver: bridge

services:
  app:
    build:
      args:
        user: developer
        uid: 6543
      context: ./
      dockerfile: Dockerfile
    image: php-composer
    container_name: php-composer
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      # - ./src:/var/www
      - ./docker/php-config/php.ini:/usr/local/etc/php/conf.d/php.ini:cached
      - ./src:/var/www/html:delegated
    networks:
      - devcrown
  nginx:
      image: nginx:stable-alpine
      container_name: nginx
      ports:
        - "8000:80"
      volumes:
        - ./src:/var/www/html:cached
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
      networks:
        - devcrown